[package]
name = "wpilog-parser"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
memmap2 = "0.9"
rmpv = "1.3"
arrow = { version = "57.0.0", default-features = false, features = ["prettyprint"] }
parquet = { version = "57.0.0", default-features = false, features = ["arrow", "lz4", "snap", "brotli"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
byteorder = "1.5"
thiserror = "2.0"
tokio = { version = "1.40", features = ["rt", "sync"], optional = true }

[features]
default = []
tokio-runtime = ["tokio"]

[dev-dependencies]
hex = "0.4"
tempfile = "3.8"
tokio = { version = "1.40", features = ["rt", "sync", "macros"] }
